export default {
  'flat-surface-current-speed': {
    key: 'flat-surface-current-speed',
    name: 'Surface current speed',
    imagePrefix: 's3llg:',
    style: 'flat',
    type: 'sea',
    hasLegend: true,
  },
  'flat-sig-wave-height': {
    key: 'flat-sig-wave-height',
    name: 'Significant wave (flat)',
    imagePrefix: 's3llg:',
    style: 'flat',
    type: 'sea',
    hasLegend: true,
  },
  'flat-precip-in-3hrs': {
    key: 'flat-precip-in-3hrs',
    name: 'Precipitation in 3hrs',
    imagePrefix: 's3llg:',
    style: 'flat',
    type: 'weather',
    hasLegend: true,
  },
  'flat-relative-humidity': {
    key: 'flat-relative-humidity',
    name: 'Relative humidity',
    imagePrefix: 's3llg:',
    style: 'flat',
    type: 'weather',
    hasLegend: true,
  },
  'flat-wind-speed': {
    key: 'flat-wind-speed',
    name: 'Wind speed',
    imagePrefix: 's3llg:',
    style: 'flat',
    type: 'weather',
    hasLegend: true,
  },
  'flat-visibility': {
    key: 'flat-visibility',
    name: 'Visibility',
    imagePrefix: 's3llg:',
    style: 'flat',
    type: 'weather',
    hasLegend: true,
  },
  'primary-wave-direction': {
    key: 'primary-wave-direction',
    name: 'Primary wave direction',
    imagePrefix: 's3llg:',
    style: 'other',
    type: 'sea',
    hasLegend: false,
  },
  'sig-wave-height': {
    key: 'sig-wave-height',
    name: 'Significant wave (gradient)',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'sea',
    hasLegend: true,
  },
  'wind-wave-height': {
    key: 'wind-wave-height',
    name: 'Wind wave height',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'sea',
    hasLegend: true,
  },
  'wind-wave-period': {
    key: 'wind-wave-period',
    name: 'Wind wave period',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'sea',
    hasLegend: true,
  },
  'wind-wave-direction': {
    key: 'wind-wave-direction',
    name: 'Wind wave direction',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'sea',
  },
  'swell-height': {
    key: 'swell-height',
    name: 'Swell height',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'sea',
    hasLegend: true,
  },
  'swell-period': {
    key: 'swell-period',
    name: 'Swell period',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'sea',
    hasLegend: true,
  },
  'swell-direction': {
    key: 'swell-direction',
    name: 'Swell direction',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'sea',
  },
  'surface-currents': {
    key: 'surface-currents',
    name: 'Surface currents',
    imagePrefix: 's3llg:',
    style: 'other',
    type: 'sea',
  },
  'air-pressure': {
    key: 'air-pressure',
    name: 'Air pressure',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'weather',
  },
  'wind-speed-at-10m': {
    key: 'wind-speed-at-10m',
    name: 'Wind speed at 10m',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'weather',
    hasLegend: true,
  },
  'wind-barbs': {
    key: 'wind-barbs',
    name: 'Wind barbs',
    imagePrefix: 's3llg:',
    style: 'other',
    type: 'weather',
  },
  'relative-humidity': {
    key: 'relative-humidity',
    name: 'Relative humidity',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'weather',
    hasLegend: true,
  },
  'surface-temp': {
    key: 'surface-temp',
    name: 'Surface temp',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'weather',
    hasLegend: true,
  },
  'air-temp-at-2m': {
    key: 'air-temp-at-2m',
    name: 'Air temp at 2m',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'weather',
    hasLegend: true,
  },
  'cloud-cover': {
    key: 'cloud-cover',
    name: 'Cloud cover %',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'weather',
    hasLegend: true,
  },
  '1000-500mb-thickness': {
    key: '1000-500mb-thickness',
    name: '1000 - 500mb thickness',
    imagePrefix: 's3llg:',
    style: 'other',
    type: 'weather',
  },
  precipitation: {
    key: 'precipitation',
    name: 'Precipitation',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'weather',
    hasLegend: true,
  },
  'ice-cover': {
    key: 'ice-cover',
    name: 'Ice cover',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'sea',
    hasLegend: true,
  },
  iceedge: {
    key: 'iceedge',
    name: 'Ice edge',
    style: 'flat',
    type: 'sea',
    hasLegend: false,
    dateFormat: 'YYYY-MM-DD',
  },
  icebergs: {
    key: 'icebergs',
    name: 'Icebergs',
    style: 'flat',
    type: 'sea',
    hasLegend: false,
    dateFormat: 'YYYY-MM-DD',
  },
  visibility: {
    key: 'visibility',
    name: 'Visibility',
    imagePrefix: 's3llg:',
    style: 'gradient',
    type: 'weather',
    hasLegend: true,
  },
  trs: {
    key: 'trs',
    name: 'Tropical Storms',
    style: 'flat',
    type: 'weather',
  },
};
